/**
 * @file OpenAIAdapter.ts
 * Adapter wrapping modern OpenAI Chat/Responses API.
 * Experimental: Supports textual input and output.
 */

import { BaseAdapter } from '../custom/BaseAdapter.js';
import { normalizeAgentCard, logger } from 'a2a-mesh';
import type { AnyAgentCard, Task, Message, Artifact, Part, TextPart } from 'a2a-mesh';
import type OpenAI from 'openai';

export class OpenAIAdapter extends BaseAdapter {
  private client: OpenAI;
  private model: string;
  private systemPrompt: string | undefined;

  constructor(card: AnyAgentCard, client: OpenAI, model: string = 'gpt-4o', systemPrompt?: string) {
    super(normalizeAgentCard(card));
    this.client = client;
    this.model = model;
    this.systemPrompt = systemPrompt;
  }

  async handleTask(task: Task, message: Message): Promise<Artifact[]> {
    logger.info(`OpenAI processing task ${task.id}`);

    // Map A2A task history + current message to OpenAI Messages
    const openAiMessages: OpenAI.Chat.ChatCompletionMessageParam[] = [];

    if (this.systemPrompt) {
      openAiMessages.push({ role: 'system', content: this.systemPrompt });
    }

    if (task.history) {
      for (const histMsg of task.history) {
        if (histMsg.messageId === message.messageId) continue;
        const text = this.extractText(histMsg.parts);
        if (text) {
          openAiMessages.push({
            role: histMsg.role === 'agent' ? 'assistant' : 'user',
            content: text,
          });
        }
      }
    }

    const currentText = this.extractText(message.parts);
    if (!currentText) {
      throw new Error('OpenAI Adapter requires text input');
    }

    openAiMessages.push({
      role: message.role === 'agent' ? 'assistant' : 'user',
      content: currentText,
    });

    const response = await this.client.chat.completions.create({
      model: this.model,
      messages: openAiMessages,
    });

    const outputContent = response.choices[0]?.message?.content;
    if (!outputContent) {
      throw new Error('OpenAI returned empty response');
    }

    const partsOut: Part[] = [{ type: 'text', text: outputContent }];

    const artifact: Artifact = {
      artifactId: `oai-art-${Date.now()}`,
      name: 'OpenAI Response',
      description: 'Result generated by OpenAI Chat API',
      parts: partsOut,
      index: 0,
      lastChunk: true,
    };

    return [artifact];
  }

  private extractText(parts: Part[]): string {
    return parts
      .filter((p): p is TextPart => p.type === 'text')
      .map((p) => p.text)
      .join('\n');
  }
}
